### ISSUE TITLE
After the web page loads dilithium.js, an error occurs when executing DilithiumKeyPair.generate(2)

### ISSUE THREAD

**Issue by derekcmini** [AgustinSRG/crystals-dilithium-js#1]
Hi,
I use **<script type="text/javascript" src="/path/to/dilithium.js"></script>** in my html code, and
Part of the js code in my frontend:
**const level = DilithiumAlgorithm.DilithiumLevel.get(2);
const keyPair = DilithiumAlgorithm.DilithiumKeyPair.generate(level);**

Post-processing when web page is reloaded

 **ReferenceError: Buffer is not defined
    at s (dilithium.js:2:63339)
    at l.generate (dilithium.js:2:42255)**

Am I doing anything wrong?

**Comment by AgustinSRG** [comment]
Hello. Thanks for reporting this issue.

It seems Webpack does not include a `Buffer` polyfill into the javascript library bundle by default. I changed the webpack configuration to include it. Now it should be working without any extra dependencies in the browser (https://github.com/AgustinSRG/crystals-dilithium-js/releases/tag/v1.1.1).

I also added a basic test page (https://agustinsrg.github.io/crystals-dilithium-js/test.html) to test the browser bundle.

I'm marking the issue as completed. In case you find any other issues with this library, feel free to open more issues in the future.
